steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-south1-docker.pkg.dev/calculator-453018/calculator-repo/calculus-backend", "."]

  # Step 2: Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-south1-docker.pkg.dev/calculator-453018/calculator-repo/calculus-backend"]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: [
      "gcloud", "run", "deploy", "calculus-backend",
      "--image", "asia-south1-docker.pkg.dev/calculator-453018/calculator-repo/calculus-backend",
      "--platform", "managed",
      "--region", "asia-south1",
      "--allow-unauthenticated",
      "--port", "8080",
      "--set-env-vars", "PORT=8080"
    ]
